pimcore_data_hub:
    configurations:
        products:
            general:
                active: true
                type: dataImporterDataObject
                name: products
                description: ''
                group: ''
                path: null
                modificationDate: 1745743619
                createDate: 1745738592
            loaderConfig:
                type: asset
                settings:
                    assetPath: '/csv/Handbags and Clutches.csv'
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    saveHeaderName: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: '2'
                loadingStrategy:
                    type: notLoad
                createLocationStrategy:
                    type: findOrCreateFolder
                    settings:
                        dataSourceIndex: sub_category
                        fallbackPath: /backup
                locationUpdateStrategy:
                    type: staticPath
                    settings:
                        path: /backup
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: parallel
                idDataIndex: name
                cleanup:
                    strategy: delete
            mappingConfig:
                -
                    label: name
                    dataSourceIndex:
                        - name
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: main_category
                    dataSourceIndex:
                        - main_category
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: main_category
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: sub_category
                    dataSourceIndex:
                        - sub_category
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: sub_category
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: image
                    dataSourceIndex:
                        - image
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: image
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: link
                    dataSourceIndex:
                        - link
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: link
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: ratings
                    dataSourceIndex:
                        - ratings
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: ratings
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: no_of_ratings
                    dataSourceIndex:
                        - no_of_ratings
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: ratings
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: discount_price
                    dataSourceIndex:
                        - discount_price
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: discount_price
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: actual_price
                    dataSourceIndex:
                        - actual_price
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: actual_price
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
